### ISSUE TITLE
Help me! The script is not running.

### ISSUE THREAD

**Issue by valek333** [hansalemaos/geteventplayback#1]
After installation, I launch the script using a .bat file.
Then I encounter some errors.

C:\Python\Lib\site-packages\geteventplayback>python record.py
Press ENTER to stop
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\geteventplayback\record.py", line 44, in <module>
    results = pla.start_recording()
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\geteventplayback\__init__.py", line 176, in start_recording
    finalresults = self._get_files_and_cmd(unpacked_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\geteventplayback\__init__.py", line 193, in _get_files_and_cmd
    clusteredevents = list_split(
                      ^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\geteventplayback\__init__.py", line 20, in list_split
    raise ValueError("number sections must be larger than 0.") from None
ValueError: number sections must be larger than 0.

C:\Python\Lib\site-packages\geteventplayback>pause

What could be the cause of the error? Please help me. I've been searching for a solution like this for a long time.

OS Windows 11
Python 3.11
Emulator android - Nox (android 9)

**Comment by hansalemaos** [comment]
Is there any output while the recording is going on?

Important: Is root activated?

**Comment by valek333** [comment]
Root enabled (Magisk)

If you are talking about the output of data to the tempfolder_hdd directory, then it is empty.

**Comment by valek333** [comment]
I also tried running the Memu emulator, but I encountered errors as well.

**Comment by hansalemaos** [comment]
Do you see any output like in the video?

**Comment by valek333** [comment]
Perhaps I am doing something wrong? This is my first time working with Python.

import subprocess

from geteventplayback import GeteventPlayBack

pla = GeteventPlayBack(
    adb_path=r"C:\Android\android-sdk\platform-tools\adb.exe",
    device="/dev/input/event4",
    device_serial="127.0.0.1:5555",
    print_output=True,
    tmpfolder_device="/sdcard/event4/",
    tempfolder_hdd=rf"C:\sadxxxxxxxxxxxx",
    add_closing_command=True,
    clusterevents=16,
)

results = pla.start_recording()

subprocess.run(
    [pla.adb_path, "-s", pla.device_serial, "shell"],
    bufsize=0,
    input=results["adbcommand"],  # Can be resused
)

In the code above, I insert my own parameters. Then, I save it as a record.py file. Next, I create a .bat file and write "python record.py" inside it. After that, I run the .bat file, and that's where the issues arise (as seen in the screenshot). The screen data is not being recorded (as shown in your example video). When I press enter, errors appear.

![3](https://github.com/hansalemaos/geteventplayback/assets/109709322/e8dfc045-638d-410f-99f4-3c2e285dec8b)

**Comment by hansalemaos** [comment]
I don't see any byte output on the cmd.exe screen, so it seems that it isn't recording. Are you sure that this is the right device? /dev/input/event4

**Comment by valek333** [comment]
Yes, the value is set correctly. Here is the data from my file.

import subprocess

from geteventplayback import GeteventPlayBack

pla = GeteventPlayBack(
    adb_path=r"C:\SDK\platform-tools\adb.exe",
    device="/dev/input/event4",
    device_serial="127.0.0.1:62025",
    print_output=True,
    tmpfolder_device="/sdcard/event6/",
    tempfolder_hdd=rf"C:\sadxxxxxxxxxxxx",
    add_closing_command=True,
    clusterevents=16,
)

results = pla.start_recording()

subprocess.run(
    [pla.adb_path, "-s", pla.device_serial, "shell"],
    bufsize=0,
    input=results["adbcommand"],  # Can be resused
![4](https://github.com/hansalemaos/geteventplayback/assets/109709322/4da4ef91-67c7-45d5-bdf3-b3e182c0fafc)

**Comment by valek333** [comment]
I have found the mistake. I removed "SU" from the line:

f"{self.adb_path} -s {self.device_serial} shell -- cat {self.device}",

and now everything is working!

**Comment by valek333** [comment]
Although, no. Now everything is displaying and recording, but it is not playing back.

**Comment by hansalemaos** [comment]
Su is needed to replay it. It seems like that there is something wrong with your root rights. Su doesn't work when there the device is not rooted correctly

**Comment by andrewcharlwood** [comment]
Hey,

Also had a similar issue to OP, not sure this is a roots right issue though. I used ADB via command line but was able to use su, and then run the command "cat /dev/input/event2" without issue.

To confirm, my issue was the despite the code looking good to go (With the press ENTER to stop text), no events were being recorded/output. 

Instead of removing su, i replaced "--" with "&" which made everything work (and I'm thankful because this repo is going to save me a significant amount of time!).

I don't know enough about using adb/shell to know if replacing with & makes any sense, it was more of a lucky punt! But can confirm that it's not root privileges necessarily causing the issues OP is describing.

**Comment by hansalemaos** [comment]
Thank you! I am glad that the code helped you. What do you mean? Do you want to join all command lines in a single huge one?

**Comment by andrewcharlwood** [comment]
Apologies, I should have been clearer. [Line 159 of the init file](https://github.com/hansalemaos/geteventplayback/blob/345e53f2340cb2083b55d5f0fa712feb46b0606e/__init__.py#L159C7-L160C10):

`f"{self.adb_path} -s {self.device_serial} shell su -- cat {self.device}", stdout=subprocess.PIPE,`

I was having the same issue as described above, where everything looks like it's running but the program is unable to record/log event data. After changing the above line (and 252 in the same way) to:

`f"{self.adb_path} -s {self.device_serial} shell su & cat {self.device}", stdout=subprocess.PIPE,`

It worked correctly for me:

https://github.com/hansalemaos/geteventplayback/assets/44037977/3ee1fbe3-21e9-4e04-b158-3d2efbda3621
