### ISSUE TITLE
Playing recorded event without recording new getevent.

### ISSUE THREAD

**Issue by Epaann** [hansalemaos/geteventplayback#2]
Hi! Thanks for sharing the code!

I run the code on cmd.exe and its working fine, but I want to tweak the code so I can play the recorded event without recording a new getevent. Is there a way to do this?? Thanks in advance.

**Comment by hansalemaos** [comment]
Of course :) 
```
subprocess.run(
    [pla.adb_path, "-s", pla.device_serial, "shell"],
    bufsize=0,
    input=results["adbcommand"],  # just write down the string that you get here: results["adbcommand"] - something like su -c "...." and you can use it as much as you want
)
```

**Comment by Epaann** [comment]
But what if I want to play the recorded event (the bin file) that has been stored in the preferred location, which I specify in tempfolder_hdd=rf"the location"?

Sorry if I used the wrong terminology and confused you

**Comment by hansalemaos** [comment]
You can the delete the files from your hdd, because they are on your device too (/sdcard/)

**Comment by Epaann** [comment]
If I run the whole script without incorporating the changes you mentioned earlier, I receive a list of bin files that I can refer to as "old record". Now, I want to play this "old record" files. However, running the entire script will create "new record" file and overwriting the existing "old record" file. Is there a way to prevent the recording function and just play the "old record" file?

**Comment by hansalemaos** [comment]
Don't run the script again! It is only for creating the script. This is enough afterward:

```
import subprocess
subprocess.run(
    [adb_path, "-s", device_serial, "shell"],
    bufsize=0,
    input=YOUR COMMAND STRING,  # just write down the string that you get from: results["adbcommand"] - something like su -c "...." and you can use it as much as you want
)
```

**Comment by Epaann** [comment]
Thank you for your patience and always responding, now I understand what you mean and the code works! :)

Here's the code if anyone wants to do the same thing
```
import subprocess

adb_path=                    #adb.exe address
device_serial=               #your emu/andro ip:port
   
subprocess.run(
    [adb_path, "-s", device_serial, "shell"],
    bufsize=0,
    input= (your string command) ,  #do print(results["adbcommand"]) copy & paste the result
)
```

**Comment by hansalemaos** [comment]
Perfect!! I am happy that it worked out! Are you using an emulator or a real rooted device?

**Comment by Epaann** [comment]
an emulator

**Comment by hansalemaos** [comment]
Awesome! I haven't had a chance yet to test it on a real device. I would like to know if it works. I am going to close this here, ok?
